spring.datasource.url=jdbc:postgresql://localhost:5432/frms
spring.datasource.username=postgres
spring.datasource.password=root

jwt.secret=MySuperSecretKeyForFRMSApplicationJwtAuthentication2025

spring.mail.username=pratyush.tripathi@secureedge.in
spring.mail.password=pciz iicq gnpu rtec

sms.msg24x7.api-key=${MSG24X7_API_KEY}
sms.msg24x7.client-id=${MSG24X7_CLIENT_ID}
app.internal.api-key=${INTERNAL_API_KEY:local-internal-key}