
spring.datasource.url=jdbc:postgresql://localhost:5432/frms
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MySuperSecretKeyForFRMSApplicationJwtAuthentication2025
jwt.expiration=600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pratyush.tripathi@secureedge.in
spring.mail.password=pciz iicq gnpu rtec


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
