
spring.datasource.url=jdbc:postgresql://localhost:5432/frms
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MySuperSecretKeyForFRMSApplicationJwtAuthentication2025
jwt.expiration=600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=archita.gupta@secureedge.in
spring.mail.password=pciz iicq gnpu rtec


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.root=INFO
logging.level.com.se_frms=DEBUG
logging.file.name=logs/frms.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

sms.msg24x7.send-url=https://control.msg24x7.com/api/v2/SendSMS
sms.msg24x7.api-key=${MSG24X7_API_KEY}
sms.msg24x7.client-id=${MSG24X7_CLIENT_ID}
sms.msg24x7.sender-id=SCEDGE
sms.msg24x7.template-id=1707166453043969528
sms.msg24x7.principle-entity-id=1701166436728776010
sms.msg24x7.login-otp-message=Dear partner, your login otp is {otp} Don't share with anyone Regards Secureedge Fintech Pvt Ltd

sms.otp.return-in-response=false
