spring.datasource.url=jdbc:postgresql://localhost:5432/FRMS_DEV
spring.datasource.username=postgres
spring.datasource.password=Archita123

jwt.secret=MySuperSecretKeyForFRMSApplicationJwtAuthentication2025

spring.mail.username=archita.gupta@secureedge.in
spring.mail.password=oybefzqntbnpdaib

sms.msg24x7.api-key=${MSG24X7_API_KEY}
sms.msg24x7.client-id=${MSG24X7_CLIENT_ID}